# Generated by Django 3.0.8 on 2020-08-11 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Polno ime COVID bolnišnice.', max_length=35)),
                ('short_name', models.CharField(help_text='Kratica COVID bolnišnice.', max_length=10)),
                ('is_active', models.BooleanField(help_text='Ali je bolnišnica trenutno aktivna?')),
            ],
        ),
        migrations.CreateModel(
            name='ReportHOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hospitalized', models.IntegerField(default=0, help_text='Število vseh hospitaliziranih COVID')),
                ('total_hospitalized_ICU', models.IntegerField(default=0, help_text='Število hospitaliziranih COVID na intenzivni negi')),
                ('total_released', models.IntegerField(default=0, help_text='Število odpuščenih COVID')),
                ('total_deaths', models.IntegerField(default=0, help_text='Število smrtnih primerov s COVID')),
                ('deaths_info', models.CharField(help_text='Spol M/Ž in starost umrlih, npr. M70 Ž85', max_length=100)),
                ('remark', models.CharField(help_text='Opomba, pojasnilo', max_length=100)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOS.Hospital')),
            ],
        ),
    ]
