# Generated by Django 3.1 on 2020-08-14 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Polno ime COVID bolnišnice')),
                ('short_name', models.CharField(max_length=30, verbose_name='Kratica COVID bolnišnice')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ali je bolnišnica trenutno aktivna?')),
            ],
            options={
                'verbose_name': 'Bolnica',
                'verbose_name_plural': 'Bolnice',
                'ordering': ('-is_active', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Report_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Polno ime poročila')),
                ('short_name', models.CharField(max_length=8, verbose_name='Kratica poročila')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ali je poročilo trenutno aktivno?')),
                ('recipients', models.TextField(blank=True, help_text='Prejemnike poročila ločite z vejicami.', null=True, verbose_name='Email adrema')),
            ],
            options={
                'verbose_name': 'Tip poročila',
                'verbose_name_plural': 'Tip poročil',
                'ordering': ('short_name',),
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zadnja sprememba')),
                ('send_partial_report', models.TimeField()),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOS.report_type')),
            ],
            options={
                'verbose_name': 'Urnik pošiljanja',
                'verbose_name_plural': 'Urnik pošiljanj',
                'ordering': ('report_type',),
            },
        ),
        migrations.CreateModel(
            name='ReportHOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_form_saved', models.DateTimeField(auto_now_add=True)),
                ('date_reporting', models.DateField(default=django.utils.timezone.now, help_text='LLLL-MM-DD', verbose_name='Datum poročila')),
                ('total_hospitalized', models.PositiveIntegerField(blank=True, null=True, verbose_name='Število vseh hospitaliziranih COVID')),
                ('total_hospitalized_ICU', models.PositiveIntegerField(blank=True, null=True, verbose_name='Število hospitaliziranih COVID na intenzivni negi')),
                ('total_released', models.PositiveIntegerField(blank=True, null=True, verbose_name='Število odpuščenih COVID')),
                ('total_deaths', models.PositiveIntegerField(blank=True, null=True, verbose_name='Število smrtnih primerov s COVID')),
                ('deaths_info', models.CharField(blank=True, help_text='Spol M/Ž in starost umrlih, npr. M70 Ž85', max_length=100, null=True, verbose_name='Informacije o preminulih')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Opombe')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOS.hospital')),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOS.report_type')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poročilo bolnice',
                'verbose_name_plural': 'Poročila bolnic',
                'ordering': ('-date_reporting', 'hospital'),
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('date_report_sent', models.DateField(default=django.utils.timezone.now, help_text='LLLL-MM-DD', verbose_name='Datum poslanega emaila')),
                ('date_report_sent_for', models.DateField(default=django.utils.timezone.now, help_text='LLLL-MM-DD', verbose_name='Datum poročanja')),
                ('full_report_sent', models.BooleanField(default=False, verbose_name='Popolno poročilo (vse aktivne bolnice)')),
                ('partial_report_sent', models.BooleanField(default=False, verbose_name='Delno poročilo (samo nekatere bolnice)')),
                ('recipients', models.TextField(blank=True, null=True, verbose_name='Email adrema')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Vsebina')),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HOS.report_type')),
            ],
            options={
                'verbose_name': 'Poslano sporočilo',
                'verbose_name_plural': 'Poslana sporočila',
                'ordering': ('date_report_sent', 'date_report_sent', 'report_type', 'full_report_sent', 'partial_report_sent'),
            },
        ),
    ]
