# Generated by Django 3.1 on 2020-08-17 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HOS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_type',
            name='send_partial_report',
            field=models.TimeField(default='10:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report_type',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Zadnja sprememba'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
