# Generated by Django 3.1 on 2020-08-14 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HOS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ('date_report_sent', 'date_report_sent_for', 'report_type', 'full_report_sent', 'partial_report_sent'), 'verbose_name': 'Poslano sporočilo', 'verbose_name_plural': 'Poslana sporočila'},
        ),
        migrations.AlterField(
            model_name='reporthos',
            name='date_reporting',
            field=models.DateField(default=django.utils.timezone.now, help_text='LLLL-MM-DD', verbose_name='Datum, za katerega poročamo'),
        ),
    ]
