# Generated by Django 3.0.8 on 2020-08-11 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthos',
            name='date_reporting',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 21, 48, 8, 18541), verbose_name='Date'),
        ),
    ]
