# Generated by Django 3.0.8 on 2020-08-11 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOS', '0002_reporthos_date_reporting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Ali je bolnišnica trenutno aktivna?'),
        ),
        migrations.AlterField(
            model_name='reporthos',
            name='date_reporting',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 22, 5, 9, 289512), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reporthos',
            name='deaths_info',
            field=models.CharField(blank=True, help_text='Spol M/Ž in starost umrlih, npr. M70 Ž85', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reporthos',
            name='remark',
            field=models.CharField(blank=True, help_text='Opomba, pojasnilo', max_length=100, null=True),
        ),
    ]
