# Generated by Django 3.1 on 2020-08-14 14:51

import HOS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOS', '0002_auto_20200814_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthos',
            name='date_reporting',
            field=models.DateField(default=HOS.models.ReportHOS.yesterday, help_text='DD.MM.LLLL', verbose_name='Datum, za katerega poročamo'),
        ),
        migrations.AlterField(
            model_name='reporthos',
            name='report_type',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Tip poročila - short name'),
        ),
    ]
