# Generated by Django 3.1 on 2020-08-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOS', '0002_auto_20200817_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Email_log',
        ),
        migrations.AlterField(
            model_name='report_type',
            name='recipients',
            field=models.TextField(blank=True, help_text='Email vsakega prejemnika poročila vpišite v svojo vrsto, vpišite samo brez dodatnih znakov.', null=True, verbose_name='Email adrema'),
        ),
    ]
