# Generated by Django 3.0.8 on 2020-08-11 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOS', '0003_auto_20200811_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthos',
            name='date_reporting',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 22, 11, 57, 71018), verbose_name='Date'),
        ),
    ]
