# Generated by Django 3.0.8 on 2020-08-11 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOS', '0004_auto_20200811_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthos',
            name='date_reporting',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 22, 15, 57, 654897), verbose_name='Date'),
        ),
    ]
