# Generated by Django 3.0.8 on 2020-08-11 21:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOS', '0013_auto_20200811_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthos',
            name='submitted_by',
            field=models.CharField(default=1, help_text='Polno ime COVID bolnišnice.', max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporthos',
            name='date_reporting',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 23, 43, 24, 126536), verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskn', models.CharField(max_length=400)),
                ('usern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
