# Generated by Django 3.0.8 on 2020-08-11 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOS', '0015_auto_20200811_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthos',
            name='date_reporting',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 23, 55, 53, 88021), verbose_name='Date'),
        ),
    ]
