# Generated by Django 3.0.8 on 2020-08-11 21:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOS', '0016_auto_20200811_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthos',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporthos',
            name='date_reporting',
            field=models.DateField(default=datetime.datetime(2020, 8, 11, 23, 56, 57, 451155), verbose_name='Date'),
        ),
    ]
