# Generated by Django 3.0.8 on 2020-08-11 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOS', '0018_auto_20200812_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthos',
            name='date_reporting',
            field=models.DateField(default=datetime.datetime(2020, 8, 12, 0, 14, 11, 172752), verbose_name='Date'),
        ),
        migrations.DeleteModel(
            name='TaskItem',
        ),
    ]
