# Generated by Django 3.0.8 on 2020-08-11 22:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOS', '0019_auto_20200812_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthos',
            name='date_reporting',
            field=models.DateField(default=datetime.datetime(2020, 8, 12, 0, 23, 23, 777153), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reporthos',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
